language: rust
rust:
  - 1.37.0
  - stable
  - nightly
sudo: false
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
env:
  global:
    - RUSTFLAGS="--deny warnings"
    - RUST_BACKTRACE=1
  matrix:
    - FEATURES=""  # default configuration (with reqwest)
    - FEATURES="--no-default-features"
script:
  - cargo test $FEATURES
  - du -hs ~/.cargo
  - du -hs *
