language: rust
rust:
  - 1.21.0
  - stable
  - nightly
cache: cargo
sudo: false
env:
  global:
    - RUSTFLAGS="--deny warnings"
    - RUST_BACKTRACE=1
  matrix:
    - FEATURES=""  # default configuration (with reqwest)
    - FEATURES="--no-default-features"
script: cargo test $FEATURES
