[package]
authors = ["Jonas Schievink <jonasschievink@gmail.com>"]
description = "An XML-RPC implementation for Rust"
documentation = "https://docs.rs/xmlrpc/"
repository = "https://github.com/jonas-schievink/xml-rpc-rs.git"
keywords = ["xml", "rpc", "remote", "ipc"]
categories = ["network-programming", "encoding"]
readme = "README.md"
license = "CC0-1.0"
name = "xmlrpc"
version = "0.9.0"

[dependencies]
base64 = "0.9.0"
iso8601 = "0.2.0"
xml-rs = "0.7.0"
reqwest = { version = "0.8.0", optional = true }

[features]
default = ["reqwest"]

[[example]]
name = "client"
required-features = ["reqwest"]

[[example]]
name = "custom-header"
required-features = ["reqwest"]

# cargo-release configuration
[package.metadata.release]
tag-message = "{{version}}"
no-dev-version = true
